//
//  DeveloperPreview.swift
//  AirbnbTutorial
//
//  Created by Büşra Gedikoğlu on 25.09.2024.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4, 
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageUrls: ["listing-1","listing-2","listing-3","listing-4"],
              adress: "124 Main St",
              city: "Miami", 
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type: .villa
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4, 
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7706,
              longitude: -80.1340,
              imageUrls: ["listing-2","listing-5","listing-3","listing-4"],
              adress: "124 Main St",
              city: "Miami", 
              state: "Florida",
              title: "Miami Beach House",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .tv, .kitchen, .office],
              type: .house
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Steve Johnson",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4, 
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 25.7650,
              longitude: -80.1936,
              imageUrls: ["listing-3","listing-2","listing-7","listing-4"],
              adress: "124 Main St",
              city: "Miami", 
              state: "Florida",
              title: "Beautiful Miami apartment in downtown Brickell",
              rating: 4.32,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "harry Styles",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 34.2,
              longitude: -118.0426,
              imageUrls: ["listing-7","listing-2","listing-3","listing-4"],
              adress: "124 Main St",
              city: "Los Angeles",
              state: "California",
              title: "Beautiful Los Angeles home is Malibu",
              rating: 4.97,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .pool],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Timothy Chalamet",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 34.1,
              longitude: -118.1426,
              imageUrls: ["listing-8","listing-2","listing-3","listing-4"],
              adress: "124 Main St",
              city: "Los Angeles",
              state: "California",
              title: "Beautiful Los Angeles home in the Hollywood Hills",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              type: .apartment
             ),
    ]
}
